{
 "title": "Network UPS Tools",
 "description": "Dashboard for Network UPS Tools https://github.com/vkorobov/ups-telegraf",
 "tags": [
  "ups",
  "NUT"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"ups_nut\" with key = \"host\""
   },
   {
    "name": "maxwatt",
    "label": "UPS Max Output Power Capacity (Watt)",
    "query": "480,500,600,700,800,865,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000"
   },
   { "name": "currency", "label": "Pénznem", "query": "Ft,$,€,£,C$,kr,₽,¥" },
   {
    "name": "kwhprice",
    "label": "az áram kWh ára",
    "query": "80,81,82,83,84,85,86,87,88,89,90"
   }
  ]
 },
 "panels": [
  {
   "title": "UPS Brand",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.mfr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Napi fogyasztás",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* .01 * $maxwatt/1000/365*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heti fogyasztás",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* .01 * $maxwatt/1000/52*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Havi fogyasztás",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* .01 * $maxwatt/1000/12*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Várható éves fogyasztás",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "* .01 * $maxwatt/1000*24*$kwhprice*365"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS model",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .01 * $maxwatt" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Load kWh",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .01 * $maxwatt/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime on battery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "battery.runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Beep status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.beeper.status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Output voltage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "output.voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Input voltage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "input.voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "battery.charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Output voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Output voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "output.voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Input voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "input.voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Battery charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "battery.charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "battery.runtime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_nut",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}